### ISSUE TITLE
.NET 4.5.1 support

### ISSUE THREAD

**Issue by jisotalo** [jchristn/LoggingModule#2]
Hi! 

I tried your project and it seems quite useful and simple logger, great! I'm working with a system using .NET Framework 4.5.1 and updating is not possible at the moment. Do you think you could change the dependency to that one?

I cloned and built using 4.5.1 and seems to work fine for at least me!  If it's not possible, it's okay. I'm just building it myself then.

Ps. Do you think it would be possible to add `virtual` keyword to different methods. like `Log` method? That would allow users to override methods to add some fancy stuff.

Regards
Jussi

**Comment by jchristn** [comment]
Hi @jisotalo great recommendation!

Please re-open if this doesn't do the trick.

NuGet: https://www.nuget.org/packages/SyslogLogging/1.3.2.6
Commit: https://github.com/jchristn/LoggingModule/commit/3ff12dab59174885c681dfad958349030383e7a4
