### ISSUE TITLE
Possibility to disable UDP logging

### ISSUE THREAD

**Issue by jisotalo** [jchristn/LoggingModule#3]
Hi again! Thank you for the previous fix, it helped a lot.

Could it be possible to add a property like `UdpEnable`? It could of course be true as default, but then it would be also possible to easily disable sending data to system log?

So if I have a situation I want to log only to console and file, it could be possible.

Thanks!

**Comment by jchristn** [comment]
Hi @jisotalo this is an excellent suggestion.  Please see the two new constructors I added in v1.3.2.7.

NuGet: https://www.nuget.org/packages/SyslogLogging/1.3.2.7
Commit: https://github.com/jchristn/LoggingModule/commit/bcee6d7a42f492735839ff9aa7ba561a8487f4cd

```csharp
// file and/or console
// bool is for enabling/disabling console
new LoggingModule("filename", true);

// file and/or console
// bool is for enabling/disabling console
new LoggingModule("filename", FileLoggingMode.FileWithDate, false);
```

Both of these internally disable UDP.
