### ISSUE TITLE
Seems to be sending the data twice.

### ISSUE THREAD

**Issue by Algernon1970** [jchristn/LoggingModule#4]
I have this code to listen for syslog traffic
`    Private Sub ListenForSyslogs()

        Dim ipeRemoteIpEndPoint As New IPEndPoint(IPAddress.Any, 0)
        Dim udpcUDPClient As New UdpClient(514)
        Dim sDataRecieve As String
        Dim bBytesRecieved() As Byte
        Dim sFromIP As String

        Try
            While True
                bBytesRecieved = udpcUDPClient.Receive(ipeRemoteIpEndPoint)
                sDataRecieve = Encoding.ASCII.GetString(bBytesRecieved)
                sFromIP = ipeRemoteIpEndPoint.Address.ToString

                FillLog(sDataRecieve, sFromIP)

                Console.WriteLine(sDataRecieve)
                sDataRecieve = ""
            End While
        Catch e As Exception
            ' just ignore for now
        End Try
    End Sub`

When, from another program I call syslog.info("Middleman checked NETSERV-STN1")
the output from that code is
`127.0.0.1,19/05/2021 11:51:11[UNKNOWN]2021-05-19 10:51:11 NETSERV-STN1 4 Info Middleman checked NETSERV-STN1
127.0.0.1,19/05/2021 11:51:11[UNKNOWN]2021-05-19 10:51:11 NETSERV-STN1 4 Info Middleman checked NETSERV-STN1`

**Comment by jchristn** [comment]
Does your ```FillLog``` method also write to the console?  Do you see this behavior with other syslog servers?

**Comment by Algernon1970** [comment]
FillLog doesn't do anything, it's an empty method where I was outputting to file, but I get the same behaviour without the FillLog method.

I've installed Kiwi Syslog Server, and that is also showing 2 entries each time I call syslog.info("Message")

Ahh, found the issue.  If your syslog server is on the localhost it receives the message twice.
If the syslog server is on a remote server, it receives the message once.

**Comment by jchristn** [comment]
Got it, thank you.  Can you please post the code that is instantiating the ```LoggingModule``` class as well?  Also what version are you using?

**Comment by jchristn** [comment]
I should also mention that if you are using 2.0+, ```127.0.0.1:514``` is automatically added to the list.  So if you're adding it, it will send to that destination twice.

**Comment by Algernon1970** [comment]
That will be what is happening. Thank you. Seems that it's by design rather
than a bug then.

**Comment by jchristn** [comment]
I will make sure to update the documentation accordingly!  Thanks for pointing this out!  Cheers, Joel
