### ISSUE TITLE
Posibble return exception if get from "SendServers"

### ISSUE THREAD

**Issue by turhany** [jchristn/LoggingModule#5]
In my flow, I need to guarantee data is sent.

Or may be you can add method to check server is accessible for example > LoggingModule.CanIAccessIt("127.0.0.1", 514)

Thank you

**Comment by jchristn** [comment]
Hi @turhany, this library, and syslog in most implementations, uses UDP, which is connectionless and provides no delivery guarantees.  

If you need delivery guarantees, I'd suggest using a different library.  One that comes to mind is [OpenAuditLog}(https://github.com/jchristn/openauditlog)

**Comment by turhany** [comment]
Hi, thank you, yes you are right I missed the point about "connectionless".

I will check your suggession.

Thank you again.
