### ISSUE TITLE
Date/time of the logs is not the local one but ever UTC universal

### ISSUE THREAD

**Issue by Skizo783** [jchristn/LoggingModule#9]
Whatever the date/time of the server/computer used to run a soft whit the SyslogLogging module, the module used UTC universal time.
The time in the logs is a crucial part to understand what happens, especially in a complex system with other softwares, so that issue render the logs generated really hard to analyze.
That could be a good idea to add a parameter to allow to configure if the date should be UTC or not, universal or not.
The only solution for the time being is to does not put {ts} in the format and manually add the date in the message, but the severity come before and it's not nice to see : 
Info 2024-08-06 10:05:26.976 : Software starting

**Comment by jchristn** [comment]
Sorry for the delay and thanks for the suggestion, uploading v2.0.7 with this now.  Check `Settings.UseUtcTime`
